# Stage 1: Build the application
FROM gradle:8.7-jdk17 AS build
COPY --chown=gradle:gradle . /chunguyen/findjob
WORKDIR /chunguyen/findjob

#skip task: test
RUN gradle clean build -x test --no-daemon

# Stage 2: Run the application
FROM openjdk:17-slim
EXPOSE 8080
COPY --from=build /chunguyen/findjob/build/libs/*.jar /chunguyen/find-job.jar
ENTRYPOINT ["java", "-jar", "/chunguyen/find-job.jar"]
